---
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.scm
  - name: ansible.utils
  - name: ansible.controller
    version: 4.6.10
  - name: ansible.hub
    version: 1.0.0
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.platform
    version: 2.5.20250326
  - name: ansible.utils
    version: 5.1.2
    version: 3.1.0
  - name: azure.azcollection
    version: 3.4.0
  - name: community.dns
    version: 3.2.4
  - name: community.general
    version: 10.6.0
  - name: community.vmware
    version: 6.0.0
  - name: community.windows
    version: 3.0.0
  - name: dellemc.unity
    version: 2.0.0
  - name: infoblox.nios_modules
    version: 1.8.0
  - name: infra.aap_configuration
    version: 3.1.0
  - name: microsoft.ad
    version: 1.9.1
  - name: vmware.vmware
    version: 2.3.0
